
-- Generated by ORDS REST Data Services 20.3.1.r3321735
-- Schema: LEAWOOD_DEV  Date: Sun Jan 03 01:52:29 2021 
--

DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'LEAWOOD_DEV',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'leawood_dev',
      p_auto_rest_auth      => TRUE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'Leawood ReST',
      p_base_path      => '/api/1.0/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'Leawood ReST',
      p_pattern        => 'alert_log',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Leawood ReST',
      p_pattern        => 'alert_log',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * 
  from lw_alert_log log
  order by log.alert_timestamp');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Leawood ReST',
      p_pattern        => 'alert_log',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => 'Creates an Alert Log message.',
      p_source         => 
'begin
    insert into lw_alert_log ( device_id, message, alert_state )
    values( :device_id, :message, ''NEW'');
end;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'Leawood ReST',
      p_pattern        => 'data_point',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Leawood ReST',
      p_pattern        => 'data_point',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'begin
    insert into lw_data_point data
    (DEVICE_ID, DEF_ID, POINT_TIMESTAMP, POINT_VALUE)
    values (
        :device_id, :data_def_id, systimestamp, :data_value
    );
end;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Leawood ReST',
      p_pattern        => 'data_point',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'select *
  from lw_data_series data
order by data.point_timestamp');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'Leawood ReST',
      p_pattern        => 'devices',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Leawood ReST',
      p_pattern        => 'devices',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select *
from lw_device device
where :serial_id is null or device.serial_id = :serial_id');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'Leawood ReST',
      p_pattern            => 'devices',
      p_method             => 'GET',
      p_name               => 'serial_id',
      p_bind_variable_name => 'serial_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

    
  ORDS.CREATE_ROLE(p_role_name => 'oracle.dbtools.role.autorest.LEAWOOD_DEV');
    
  l_roles(1) := 'oracle.dbtools.autorest.any.schema';
  l_roles(2) := 'oracle.dbtools.role.autorest.LEAWOOD_DEV';
  l_modules(1) := 'Leawood ReST';
  l_patterns(1) := '/metadata-catalog/*';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.dbtools.autorest.privilege.LEAWOOD_DEV',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'oracle.dbtools.autorest.privilege.LEAWOOD_DEV',
      p_description    => '',
      p_comments       => NULL);  

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;                                    
        
COMMIT;

END;